const express=require('express'),cors=require('cors'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken');
const {Pool}=require('pg');
const app=express();app.use(cors());app.use(express.json({limit:'5mb'}));
const PORT=process.env.PORT||10000, SECRET=process.env.JWT_SECRET;
if(!SECRET) throw new Error('JWT_SECRET is required');
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false}});
const auth=async(req,res,next)=>{try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw 0;req.user=jwt.verify(h.slice(7),SECRET);next()}catch(e){res.status(401).json({error:'Потрібна авторизація'})}};
const admin=(req,res,next)=>req.user.role==='admin'?next():res.status(403).json({error:'Потрібні права адміністратора'});
const tok=u=>jwt.sign({id:u.id,email:u.email,role:u.role,name:u.name},SECRET,{expiresIn:'30d'});
async function init(){
 await pool.query(`CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'courier',active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await pool.query(`CREATE TABLE IF NOT EXISTS routes(id BIGSERIAL PRIMARY KEY,client_id TEXT NOT NULL,owner_id BIGINT REFERENCES users(id),district TEXT NOT NULL,author TEXT NOT NULL,date TEXT,time TEXT,title TEXT,source TEXT NOT NULL DEFAULT 'Загальний',points JSONB NOT NULL DEFAULT '[]',rating_sum NUMERIC NOT NULL DEFAULT 0,rating_count INTEGER NOT NULL DEFAULT 0,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(client_id,owner_id))`);
 if(process.env.ADMIN_EMAIL&&process.env.ADMIN_PASSWORD){let e=process.env.ADMIN_EMAIL.toLowerCase();let q=await pool.query('SELECT id FROM users WHERE email=$1',[e]);if(!q.rowCount){let h=await bcrypt.hash(process.env.ADMIN_PASSWORD,12);await pool.query('INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,$4)',[process.env.ADMIN_NAME||'Адміністратор',e,h,'admin']);}}
}
app.get('/api/health',async(req,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,db:true})}catch(e){res.status(503).json({ok:false,db:false})}});
app.post('/api/register',async(req,res)=>{try{let {name,email,password}=req.body||{};email=String(email||'').trim().toLowerCase();if(!name||!email||String(password||'').length<6)return res.status(400).json({error:'Заповніть дані; пароль мінімум 6 символів'});if((await pool.query('SELECT 1 FROM users WHERE email=$1',[email])).rowCount)return res.status(409).json({error:'Такий e-mail вже існує'});let h=await bcrypt.hash(password,12),q=await pool.query('INSERT INTO users(name,email,password_hash) VALUES($1,$2,$3) RETURNING id,name,email,role',[String(name).trim(),email,h]);let u=q.rows[0];res.json({token:tok(u),email:u.email,name:u.name,role:u.role})}catch(e){console.error(e);res.status(500).json({error:'Помилка сервера'})}});
app.post('/api/login',async(req,res)=>{try{let email=String(req.body?.email||'').trim().toLowerCase(),password=String(req.body?.password||''),q=await pool.query('SELECT * FROM users WHERE email=$1 AND active=true',[email]),u=q.rows[0];if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:'Невірний e-mail або пароль'});res.json({token:tok(u),email:u.email,name:u.name,role:u.role})}catch(e){console.error(e);res.status(500).json({error:'Помилка сервера'})}});
app.get('/api/routes',auth,async(req,res)=>{try{let q=await pool.query(`SELECT client_id AS "clientId",district,author,date,time,title,source,points,rating_sum AS "ratingSum",rating_count AS "ratingCount" FROM routes WHERE source='Загальний' OR (source='Мої' AND owner_id=$1) ORDER BY updated_at DESC`,[req.user.id]);res.json({routes:q.rows})}catch(e){res.status(500).json({error:'Не вдалося отримати маршрути'})}});
app.post('/api/sync',auth,async(req,res)=>{let c=await pool.connect();try{await c.query('BEGIN');let incoming=Array.isArray(req.body?.routes)?req.body.routes:[],mine=0,general=0;for(let r of incoming){if(!r)continue;let source=r.source==='Загальний'?'Загальний':'Мої';if(source==='Загальний'&&req.user.role!=='admin')continue;let cid=String(r.clientId??r.id);await c.query(`INSERT INTO routes(client_id,owner_id,district,author,date,time,title,source,points,rating_sum,rating_count,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,NOW()) ON CONFLICT(client_id,owner_id) DO UPDATE SET district=EXCLUDED.district,author=EXCLUDED.author,date=EXCLUDED.date,time=EXCLUDED.time,title=EXCLUDED.title,source=EXCLUDED.source,points=EXCLUDED.points,rating_sum=EXCLUDED.rating_sum,rating_count=EXCLUDED.rating_count,updated_at=NOW()`,[cid,req.user.id,r.district||'',r.author||'',r.date||'',r.time||'',r.title||'',source,JSON.stringify(r.points||[]),Number(r.ratingSum||0),Number(r.ratingCount||0)]);source==='Мої'?mine++:general++}await c.query('COMMIT');let q=await pool.query(`SELECT client_id AS "clientId",district,author,date,time,title,source,points,rating_sum AS "ratingSum",rating_count AS "ratingCount" FROM routes WHERE source='Загальний' OR (source='Мої' AND owner_id=$1) ORDER BY updated_at DESC`,[req.user.id]);res.json({ok:true,savedMine:mine,savedGeneral:general,routes:q.rows})}catch(e){await c.query('ROLLBACK');console.error(e);res.status(500).json({error:'Синхронізація не виконана'})}finally{c.release()}});
app.get('/api/admin/users',auth,admin,async(req,res)=>res.json({users:(await pool.query('SELECT id,name,email,role,active,created_at FROM users ORDER BY created_at DESC')).rows}));
app.get('/api/admin/routes',auth,admin,async(req,res)=>res.json({routes:(await pool.query(`SELECT id,client_id AS "clientId",owner_id AS "ownerId",district,author,date,time,title,source,points,rating_sum AS "ratingSum",rating_count AS "ratingCount" FROM routes ORDER BY updated_at DESC`)).rows}));
app.patch('/api/admin/users/:id',auth,admin,async(req,res)=>{await pool.query('UPDATE users SET active=$1 WHERE id=$2',[!!req.body?.active,Number(req.params.id)]);res.json({ok:true})});
app.delete('/api/admin/routes/:id',auth,admin,async(req,res)=>{await pool.query('DELETE FROM routes WHERE id=$1',[Number(req.params.id)]);res.json({ok:true})});
init().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log('API ready on '+PORT))).catch(e=>{console.error(e);process.exit(1)});
